### PR TITLE
[WIP] Add CI configuration and test for building perpl.

### PR DESCRIPTION
**Pull request by chihyang**
Support using "correct" tests from [perpl](https://github.com/diprism/perpl) to test sum product of fggs. Because of one bug in [fail.ppl](https://github.com/diprism/perpl/blob/master/tests/good/fail.ppl), once this is merged, the CI will always fail. This can be merged later when the bug is fixed.

### CODE REVIEW

**Comment by ccshan** [comment]
What do you think @davidweichiang? The plan is to use PERPL tests to exercise the FGG library.

**Comment by ccshan** [comment]
> I think it sounds like a good idea. Can the CI be set up so that it is pinned to a particular version of PERPL so that a bug over there doesn't cause tests to fail here?

Good idea -- maybe a tag in the perpl repository?

**Comment by chihyang** [comment]
> > I think it sounds like a good idea. Can the CI be set up so that it is pinned to a particular version of PERPL so that a bug over there doesn't cause tests to fail here?
> 
> Good idea -- maybe a tag in the perpl repository?

If there is a tag in PERPL, I can change the CI script to always use that version. For now I just use the master branch.

**Comment by ccshan** [comment]
> If there is a tag in PERPL, I can change the CI script to always use that version. For now I just use the master branch.

Ok, I created a tag `testing` (while thinking of Debian) in the perpl repository.

Thanks for knowing how to use CI...

**Comment by ccshan** [comment]
If you merge 542ae59ab1f78b28bf1eee640a111a02abb107af then the new tests should pass?

**Review by ccshan — APPROVED** [review]

**Pull request merged**
